[profile.release]
debug = true
incremental = true
lto = "off"


[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.dependencies]
cli = { path = "crates/cli" }
motus = {path = "crates/motus"}
wasm = { path = "crates/wasm" }